config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  devise_for :users, skip: [:sessions]
  as :user do
    get '/sign-in', to: 'devise/sessions#new', as: :new_user_session
    post '/sign-in', to: 'devise/sessions#create', as: :user_session
    delete '/sign-out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :api do
    namespace :v1 do
      get '/users/:id', to: 'users#show'
      post '/user_login', to: 'users#user_login'
      post '/user_register', to: 'users#user_register'

      get '/:id', to: 'games#show', as: :direct_game
      get '/:game_id/:id', to: 'events#show', as: :direct_game_event
    end
  end

  authenticated :user, lambda {|u| u.admin } do
    resources :games do
      resources :events
    end
  end

  get '/:id', to: 'games#show', as: :direct_game
  get '/:game_id/:id', to: 'events#show', as: :direct_game_event

  scope '/:game_id/:event_id' do
    resources :posts, as: :game_event_posts
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :game
  has_many :posts
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::BaseController
  respond_to :json

  skip_before_action :authenticate_user!
  before_action :set_event

  def show
    @posts = @event.posts.order("created_at DESC")
  end

  private

  def set_event
    begin
    @event = Event.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to "/404"
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_game, only: [:index, :new, :create]

  def default_url_options
    if session[:show_navigation] == 'false'
      {:host => "hybrid", protocol: 'link'}
    else
      {}
    end
  end

  def index
    @events = @game.events.all
  end

  def show
    expires_in 1.minute, public: true # sets an cache expiration in header for ios app
    @posts = @event.posts.order("created_at DESC")
  end

  def new
    @event = @game.events.new()
  end

  def edit
  end

  def create
    @event = @game.events.new(event_params)
    if @event.save
      redirect_to game_events_path(@event.game), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to game_events_path(@event.game), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to game_events_path(@event.game), notice: 'Event was successfully destroyed.'
  end

  private

  def set_event
    begin
    @event = Event.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to "/404"
    end
  end

  def set_game
    @game = Game.friendly.find(params[:game_id])
  end

  def event_params
    params.require(:event).permit(:name, :group_size, :game_id)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event, url: game_events_path(@event.game), html: {class: 'pure-form pure-form-stacked'} do |f|
  - if @event.errors.any?
    #error_explanation.pad-10
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .pad-10
    = f.label :name
    = f.text_field :name
  .pad-10
    = f.label :group_size
    = f.number_field :group_size
  .pad-10
    = f.submit 'Save', class: 'pure-button'

app/views/events/_posts_list.html.haml
- @posts.each do |post|
  .pure-g
    .pure-u-1.pad-10
      = link_to game_event_post_url(post.game, post.event, post) do
        .pure-well
          = post.title

app/views/events/edit.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 Editing event

= render 'form'

.pure-g
  .pure-u-1.pad-10
    = link_to 'Show', game_event_path(@event.game, @event), class: 'pure-button'
    = link_to 'Back', game_events_path(@event.game), class: 'pure-button'

app/views/events/index.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 Listing events

.pure-g
  .pure-u-1.pad-10.table-responsive
    %table.pure-table
      %thead
        %tr
          %th Name
          %th Group size
          %th Game
          %th
          %th
          %th

      %tbody
        - @events.each do |event|
          %tr
            %td= event.name
            %td= event.group_size
            %td= event.game.name
            %td= link_to 'Show', direct_game_event_path(event.game, event), class: 'pure-button small'
            %td= link_to 'Edit', edit_game_event_path(event.game, event), class: 'pure-button small'
            %td= link_to 'Destroy', game_event_path(event.game, event), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'pure-button small error'

.pure-g
  .pure-u-1.pad-10
    = link_to 'New Event', new_game_event_path(@game), class: 'pure-button'

app/views/events/new.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 New event

= render 'form'

.pure-g
  .pure-u-1.pad-10
    = link_to 'Back', game_events_path(@game), class: 'pure-button'

app/views/events/show.html.haml
.pure-g
  - unless session[:show_navigation] == 'false'
    .pure-u-1.pure-u-sm-1-2.pad-10
      %h1 #{@event.game.name} / #{@event.name}
    .pure-u-1.pure-u-sm-1-2.pad-10.text-right
      = link_to "New Post", new_game_event_post_path(@event.game, @event), class: 'pure-button accent'

= render partial: 'events/posts_list'