config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  devise_for :users, skip: [:sessions]
  as :user do
    get '/sign-in', to: 'devise/sessions#new', as: :new_user_session
    post '/sign-in', to: 'devise/sessions#create', as: :user_session
    delete '/sign-out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :api do
    namespace :v1 do
      get '/users/:id', to: 'users#show'
      post '/user_login', to: 'users#user_login'
      post '/user_register', to: 'users#user_register'

      get '/:id', to: 'games#show', as: :direct_game
      get '/:game_id/:id', to: 'events#show', as: :direct_game_event
    end
  end

  authenticated :user, lambda {|u| u.admin } do
    resources :games do
      resources :events
    end
  end

  get '/:id', to: 'games#show', as: :direct_game
  get '/:game_id/:id', to: 'events#show', as: :direct_game_event

  scope '/:game_id/:event_id' do
    resources :posts, as: :game_event_posts
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :events, dependent: :destroy

end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < Api::V1::BaseController
  respond_to :json

  skip_before_action :authenticate_user!
  before_action :set_game

  def show
    @events = @game.events
  end

  private

  def set_game
    begin
    @game = Game.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to "/404"
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def default_url_options
    if session[:show_navigation] == 'false'
      {:host => "hybrid", protocol: 'link'}
    else
      {}
    end
  end

  def index
    @games = Game.all
  end

  def show
    expires_in 1.minute, public: true # sets an cache expiration in header for ios app
    @events = @game.events
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    def set_game
      begin
      @game = Game.friendly.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      redirect_to "/404"
      end
    end

    def game_params
      params.require(:game).permit(:name)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_events_list.html.haml
- @events.each do |event|
  .pure-g
    .pure-u-1.pad-10
      = link_to direct_game_event_url(event.game, event) do
        .pure-well
          = event.name

app/views/games/_form.html.haml
= form_for @game, html: {class: 'pure-form pure-form-stacked'} do |f|
  - if @game.errors.any?
    #error_explanation.pad-10
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg
  .pad-10
    = f.label :name
    = f.text_field :name
  .pad-10
    = f.submit 'Save', class: 'pure-button'

app/views/games/edit.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 Editing game

= render 'form'

.pure-g
  .pure-u-1.pad-10
    = link_to 'Show', @game, class: 'pure-button'
    = link_to 'Back', games_path, class: 'pure-button'

app/views/games/index.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 Listing games

.pure-g
  .pure-u-1.pad-10.table-responsive
    %table.pure-table
      %thead
        %tr
          %th Name
          %th
          %th
          %th

      %tbody
        - @games.each do |game|
          %tr
            %td= game.name
            %td= link_to 'Show', game, class: 'pure-button small'
            %td= link_to 'Edit', edit_game_path(game), class: 'pure-button small'
            %td= link_to 'Destroy', game, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'pure-button small error'

.pure-g
  .pure-u-1.pad-10
    = link_to 'New Game', new_game_path, class: 'pure-button'

app/views/games/new.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 New game

= render 'form'

app/views/games/show.html.haml
- unless session[:show_navigation] == 'false'
  .pure-g
    .pure-u-1.pad-10
      %h1= @game.name

= render partial: 'games/events_list'