config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  devise_for :users, skip: [:sessions]
  as :user do
    get '/sign-in', to: 'devise/sessions#new', as: :new_user_session
    post '/sign-in', to: 'devise/sessions#create', as: :user_session
    delete '/sign-out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :api do
    namespace :v1 do
      get '/users/:id', to: 'users#show'
      post '/user_login', to: 'users#user_login'
      post '/user_register', to: 'users#user_register'

      get '/:id', to: 'games#show', as: :direct_game
      get '/:game_id/:id', to: 'events#show', as: :direct_game_event
    end
  end

  authenticated :user, lambda {|u| u.admin } do
    resources :games do
      resources :events
    end
  end

  get '/:id', to: 'games#show', as: :direct_game
  get '/:game_id/:id', to: 'events#show', as: :direct_game_event

  scope '/:game_id/:event_id' do
    resources :posts, as: :game_event_posts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  has_one :game, through: :event
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_event, only: [:index, :new, :create]
  before_action :ensure_owner, only: [:edit, :update, :delete]

  def default_url_options
    if session[:show_navigation] == 'false'
      {:host => "hybrid", protocol: 'link'}
    else
      {}
    end
  end

  def index
    @posts = @event.posts.all
  end

  def show
    expires_in 1.minute, public: true # sets an cache expiration in header for ios app
  end

  def new
    @user_email = user_email
    @user_token = user_token
    @post = @event.posts.new()
  end

  def edit
  end

  def create
    @post = @event.posts.new(post_params.except(:user_email, :user_token))
    if @post.save
      redirect_to direct_game_event_url(@post.game, @post.event, {user_email: post_params[:user_email], user_token: post_params[:user_token]}), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to direct_game_event_path(@post.game, @post.event), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to direct_game_event_path(@post.game, @post.event), notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      begin
      @post = Post.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      redirect_to "/404"
      end
    end

    def set_event
      @event = Event.friendly.find(params[:event_id])
    end

    def ensure_owner
      unless @post.user == current_user || current_user.admin
        redirect_to direct_game_event_path(@post.game, @post.event), alert: 'You don\'t have permission to do that.'
      end
    end

    def post_params
      params.require(:post).permit(:title, :checkpoint, :user_id, :event_id, :user_email, :user_token)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
-# = raise 'hell'

-# This is the correct way, just need params in the form for mobile app
-# = form_for [@post.game, @post.event, @post], html: {class: 'pure-form pure-form-stacked'} do |f|

= form_for @post, url: game_event_posts_path(@post.game, @post.event, user_email: params[:user_email], user_token: params[:user_token]), html: {class: 'pure-form pure-form-stacked'} do |f|
  - if @post.errors.any?
    #error_explanation.pad-10
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .pad-10
    = f.label :title
    = f.text_field :title
  .pad-10
    = f.label :checkpoint
    = f.text_field :checkpoint

    = f.text_field :user_id, value: current_user.try(:id) || User.find_by_email(params[:user_email]).try(:id), hidden: true
    = f.text_field :user_email, value: current_user.try(:email) || User.find_by_email(params[:user_email]).try(:email), hidden: true
    = f.text_field :user_token, value: current_user.try(:auth_token) || User.find_by_email(params[:user_email]).try(:auth_token), hidden: true
  .pad-10
    = f.submit 'Save', class: 'pure-button success'

app/views/posts/_index.html.haml
.pure-g
  .pure-u-1.pad-10.table-responsive
    %table.pure-table
      %thead
        %tr
          %th Title
          %th Checkpoint
          %th User
          %th Event
          %th
          %th
          %th

      %tbody
        - @posts.each do |post|
          %tr
            %td= post.title
            %td= post.checkpoint
            %td= post.user
            %td= post.event.name
            %td= link_to 'Show', direct_game_event_post_path(post.game, post.event, post), class: 'pure-button small'
            %td= link_to 'Edit', edit_game_event_post_path(post.game, post.event, post), class: 'pure-button small'
            %td= link_to 'Destroy', game_event_post_path(post.game, post.game, post), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'pure-button small error'

.pure-g
  .pure-u-1.pad-10
    = link_to 'New Post', new_game_event_post_path(@event.game, @event), class: 'pure-button'

app/views/posts/edit.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 Editing post

= render 'form'

.pure-g
  .pure-u-1.pad-10
    = link_to 'Back', direct_game_event_path(@post.game, @post.event), class: 'pure-button'

app/views/posts/index.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 Listing posts

= render partial: 'posts/index'

app/views/posts/new.html.haml
.pure-g
  .pure-u-1.pad-10
    %h1 New post

= render 'form'

.pure-g
  .pure-u-1.pad-10
    = link_to 'Back', direct_game_event_path(@post.game, @post.event), class: 'pure-button'

app/views/posts/show.html.haml
.pure-g
  .pure-u-1.pad-10
    %p
      %b Title:
      = @post.title
    %p
      %b Checkpoint:
      = @post.checkpoint
    %p
      %b Gamertag:
      = @post.user.gamertag
    %p
      %b Event:
      = @post.event.name


.pure-g
  .pure-u-1.pad-10
    - unless session[:show_navigation] == 'false'
      = link_to 'Back', direct_game_event_path(@post.game, @post.event), class: 'pure-button'
    - if @post.user == current_user || current_admin?
      = link_to 'Edit', edit_game_event_post_path(@post.game, @post.event, @post), class: 'pure-button'
      = link_to 'Delete', game_event_post_path(@post.game, @post.game, @post), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'pure-button error'